import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Ui/Navbar/Navbar";
import { Suspense } from "react";
import Loading from "./our-teams/Loading";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Suspense fallback={<Loading/>}>

      <body suppressHydrationWarning={true}>{children}</body>
      </Suspense>
    </html>
  );
}
